export { s } from "./schema";
export type {
	ScribeArrayOptions,
	ScribeArraySchema,
	ScribeDatatypeSchema,
	ScribeDictionaryOptions,
	ScribeDictionarySchema,
	ScribeDynamicSchema,
	ScribeEnumSchema,
	ScribeNumberOptions,
	ScribeNumberSchema,
	ScribeOptionalSchema,
	ScribeSchema,
	ScribeSchemaHelpers,
	ScribeSchemaKind,
	ScribeSchemaValue,
	ScribeRuntimeSchemaDescriptor,
	ScribeStringOptions,
	ScribeStringSchema,
	ScribeTimedSchema,
	ScribeVisibility,
	ScribeVisibilitySchema,
} from "./schema";

export { scribeData } from "./definitions";
export type {
	AnyScribeData,
	ScribeArrayPath,
	ScribeArrayValueAtPath,
	ScribeClientArrayPath,
	ScribeClientDictionaryPath,
	ScribeClientPath,
	ScribeClientSchema,
	ScribeClientShape,
	ScribeDataDeclaration,
	ScribeDataDefinition,
	ScribeDataOptions,
	ScribeDictionaryPath,
	ScribeDictionaryValueAtPath,
	ScribeEconomyCurrencyDeclaration,
	ScribeEconomyDeclaration,
	ScribeEconomyFieldDeclaration,
	ScribeFullSchema,
	ScribeGiftingConfig,
	ScribeLeaderboardConfig,
	ScribeNumericPath,
	ScribePassDeclaration,
	ScribePath,
	ScribePersistedSchema,
	ScribePersistedShape,
	ScribeProductDeclaration,
	ScribePurchaseLogConfig,
	ScribeSchemaAtPath,
	ScribeSchemaOf,
	ScribeShape,
	ScribeSharedSchema,
	ScribeSharedShape,
	ScribeValueAtPath,
} from "./definitions";

export { rovyScribe } from "./registry";
export type {
	RuntimeScribeCommandDefinition,
	RuntimeScribeDataDefinition,
	RuntimeScribeEventDefinition,
} from "./registry";

export { scribeCommand } from "./commands";
export type {
	ScribeCommand,
	ScribeCommandConstructor,
	ScribeCommandHandle,
	ScribeCommandOptions,
	ScribeCommandReader,
	ScribeCommandRequest,
	ScribeCommandResponder,
	ScribeCommandResult,
	ScribeCommandResultCarrier,
	ScribeCommandResultType,
} from "./commands";

export {
	ScribeAnomaly,
	ScribeArrayInserted,
	ScribeArrayRemoved,
	ScribeCommandCompleted,
	ScribeGiftCredit,
	ScribeGiftReceived,
	ScribeIssue,
	ScribeJobCompleted,
	ScribeKeyAdded,
	ScribeKeyRemoved,
	ScribeLeaderboardChanged,
	ScribeMessageReceived,
	ScribeOwnershipChanged,
	ScribeReady,
	ScribeSaveCompleted,
	ScribeSessionEnded,
	ScribeSharedChanged,
	ScribeStatusChanged,
	ScribeUnavailable,
	ScribeValueChanged,
	scribeEvent,
} from "./events";
export type {
	ScribeArrayEventOptions,
	ScribeChangeSource,
	ScribeChangedEventOptions,
	ScribeCommandCompletedEventOptions,
	ScribeDictionaryEventOptions,
	ScribePathlessEventKind,
	ScribePathlessEventOptions,
} from "./events";

export type {
	ScribeArrayReader,
	ScribeArrayWriter,
	ScribeBooleanReader,
	ScribeBooleanWriter,
	ScribeClientReader,
	ScribeClientState,
	ScribeDictionaryReader,
	ScribeDictionaryWriter,
	ScribeInitializationArray,
	ScribeInitializationDictionary,
	ScribeInitializationNode,
	ScribeInitializationTree as ScribeInitializationSchemaTree,
	ScribeInitializationValue,
	ScribeLocalWriter,
	ScribeNumberReader,
	ScribeNumberWriter,
	ScribeReadNode,
	ScribeReadable,
	ScribeReadTree,
	ScribeServerReader,
	ScribeServerWriter,
	ScribeSharedReader,
	ScribeTimedReader,
	ScribeTimedWriter,
	ScribeValueWriter,
	ScribeWriteNode,
	ScribeWriteTree,
} from "./trees";

export type {
	ScribeCooldownState,
	ScribeCooldowns,
	ScribeDiagnostics,
	ScribeLeaderboards,
	ScribeMessaging,
	ScribeMockState,
	ScribeMonetization,
	ScribeOwnership,
	ScribePersistence,
	ScribePurchaseEntry,
	ScribePurchaseSpec,
	ScribeReceiptInfo,
	ScribeReceipts,
	ScribeSaveNowOptions,
	ScribeTestRuntime,
	ScribeUnsafe,
	ScribeUnsafeDatatypes,
} from "./services";

export {
	ACTIVE_SCRIBE_BOUNDARY,
	SCRIBE_SUPPORTED_VERSION,
	ScribeClientPlugin,
	ScribePlugin,
	ScribeServerPlugin,
	configureScribeServer,
	scribeVersion,
} from "./plugin";
export type {
	AnyConfiguredScribeServer,
	ConfiguredScribeServer,
	ScribeClientPluginOptions,
	ScribeImmediateTree,
	ScribeInitializationTree,
	ScribeMigration,
	ScribeModuleResolver,
	ScribePluginOptions,
	ScribeProcessConfiguration,
	ScribeProductGrantContext,
	ScribeServerPluginOptions,
	ScribeServerSetup,
} from "./plugin";

export {
	SCRIBE_CLIENT_READER_PREFIX,
	SCRIBE_CLIENT_STATE_PREFIX,
	SCRIBE_COMMAND_CLIENT_PREFIX,
	SCRIBE_COMMAND_READER_PREFIX,
	SCRIBE_COMMAND_RESPONDER_PARAM,
	SCRIBE_COOLDOWNS_PREFIX,
	SCRIBE_DIAGNOSTICS_PARAM,
	SCRIBE_LEADERBOARDS_PREFIX,
	SCRIBE_LOCAL_WRITER_PREFIX,
	SCRIBE_MESSAGING_PREFIX,
	SCRIBE_MONETIZATION_PREFIX,
	SCRIBE_OWNERSHIP_PREFIX,
	SCRIBE_PERSISTENCE_PREFIX,
	SCRIBE_RECEIPTS_PREFIX,
	SCRIBE_SERVER_READER_PREFIX,
	SCRIBE_SERVER_WRITER_PREFIX,
	SCRIBE_SHARED_READER_PREFIX,
	SCRIBE_TESTING_PREFIX,
	SCRIBE_UNSAFE_PREFIX,
	clientReaderParamId,
	clientStateParamId,
	commandClientParamId,
	commandReaderParamId,
	cooldownsParamId,
	leaderboardsParamId,
	localWriterParamId,
	messagingParamId,
	monetizationParamId,
	ownershipParamId,
	persistenceParamId,
	receiptsParamId,
	scribeDataParamId,
	serverReaderParamId,
	serverWriterParamId,
	sharedReaderParamId,
	testingParamId,
	unsafeParamId,
} from "./param-ids";
export type { ScribeDataParamKind } from "./param-ids";

export { ScribeReason } from "./types";
export type {
	DeepPartial,
	ReadonlyDeep,
	ScribeCtor,
	ScribeDatatypes,
	ScribeEconomyMeta,
	ScribeJobHandle,
	ScribeJobResult,
	ScribeJobResults,
	ScribeLifecycleReason,
	ScribeLeaderboardEntry,
	ScribeLogCategory,
	ScribeLogEntry,
	ScribeLogLevel,
	ScribeMetricSummary,
	ScribeNativeModule,
	ScribePrimitive,
	ScribePurchaseFilter,
	ScribePurchaseRecord,
	ScribeRobloxDatatype,
	ScribeReasonConstants,
	ScribeSaveInfo,
	ScribeSerializable,
	ScribeSessionState,
	ScribeStatus,
	ScribeStatusThresholds,
	ScribeTransactionHandle,
	ScribeTransport,
	ScribeVersionInfo,
} from "./types";
